### ISSUE TITLE
[Feature Request] Close to system tray

### ISSUE THREAD

**Issue by gabeklavans** [emmaexe/ntfyDesktop#30]
It seems pretty clear that this app is in active development, but I just wanted to put out a request for a feature I think would be quite useful/commonly requested.

Basically I want to close out the GUI window and have the app continue running in the background, accessible via a system tray icon. There's currently really no Ntfy frontend that does this for Linux that I can find.

Examples of apps that have a close to system tray option:
- https://github.com/deskflow/deskflow (has a flatpak)
- The Discord app
-  https://github.com/BlueBubblesApp/bluebubbles-app

**Comment by gabeklavans** [comment]
Welp, I just realized this app already does that. Kudos. Can't wait for the authentication update to hit flathub LOL

**Comment by emmaexe** [comment]
Yea, that is the default. Flathub is released at the same time as everything else, I just haven't had much time to work on this project recently. I'll finish up the bug fixes that I am working on and push a new version then.
